name: Run scripts

on:
  push:
    branches:
      - main

jobs:
  run_scripts:
    runs-on: windows-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up MATLAB
        uses: matlab-actions/setup-matlab@v2
        with:
          release: latest

#      - name: Set MATLAB license environment variable
#        run: |
#          echo "Setting LM_LICENSE_FILE"
#          echo "LM_LICENSE_FILE=${{ secrets.MATLAB_LICENSE_FILE }}" >> $GITHUB_ENV

      - name: Run MATLAB script 1
        working-directory: ./Matlab
        run: |
          echo "Current working directory:"
          Get-Location
          matlab -batch "run('Main_1_Data_aggregation.m')"

      - name: Run MATLAB script 2
        working-directory: ./Matlab
        run: |
          echo "Current working directory:"
          Get-Location
          matlab -batch "run('Main_2_Data_labeling.m')"

      - name: Run Python script
        working-directory: ./Python
        run: |
          echo "Current working directory:"
          Get-Location
          python Classification.py
