name: Run scripts

on:
  push:
    branches:
      - main

jobs:
  run_scripts:
    runs-on: windows-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set MATLAB license environment variable
        run: |
          echo "Setting LM_LICENSE_FILE"
          echo "LM_LICENSE_FILE=${{ secrets.MATLAB_LICENSE_FILE }}" >> $GITHUB_ENV

      - name: Set up MATLAB
        uses: matlab-actions/setup-matlab@v2.3.0
        with:
          matlab-version: 'latest'

      - name: Run MATLAB main_1
        uses: matlab-actions/run-command@v2
        with:
          command: |
            disp('Running MATLAB main_1 in folder:');
            disp(fullfile(pwd, 'Matlab'));
            cd(fullfile(pwd, 'Matlab'));
            run('Main_1_Data_aggregation.m')

      - name: Run MATLAB main_2
        uses: matlab-actions/run-command@v2
        with:
          command: |
            disp('Running MATLAB main_2 in folder:');
            disp(fullfile(pwd, 'Matlab'));
            cd(fullfile(pwd, 'Matlab'));
            run('Main_2_Data_labeling.m')

      - name: Run Python classification
        working-directory: ./Python
        run: |
          echo "Current working directory for Python script:"
          Get-Location
          python Classification.py
